DROP SCHEMA IF EXISTS db_pull_schema CASCADE;
DROP SCHEMA IF EXISTS db_pull_ext CASCADE;
CREATE SCHEMA db_pull_schema;
CREATE SCHEMA db_pull_ext;

-- external prerequisite (outside the pulled selection)
CREATE TABLE db_pull_ext.ext_ref (id bigint PRIMARY KEY);

-- types
CREATE TYPE db_pull_schema.order_status AS ENUM ('pending', 'paid', 'cancelled');
CREATE TYPE db_pull_schema.weird_labels AS ENUM ('plain', 'it''s');
CREATE DOMAIN db_pull_schema.positive_int AS integer CHECK (VALUE > 0);
CREATE TYPE db_pull_schema.money_pair AS (amount numeric, currency text);
CREATE TYPE db_pull_schema.money_bag AS (pairs db_pull_schema.money_pair[], note text);

-- sequences
CREATE SEQUENCE db_pull_schema.invoice_seq START WITH 1000 INCREMENT BY 5 CACHE 10;
CREATE SEQUENCE db_pull_schema.cyc_seq MAXVALUE 999 CYCLE;
CREATE SEQUENCE db_pull_schema.legacy_id_seq;

-- type-stage functions
CREATE FUNCTION db_pull_schema.norm_email(text) RETURNS text
LANGUAGE sql IMMUTABLE AS $$ SELECT lower(trim($1)) $$;

CREATE FUNCTION db_pull_schema.crlf_fn() RETURNS integer
LANGUAGE plpgsql AS E'BEGIN\r\n  RETURN 1;\r\nEND';

CREATE FUNCTION db_pull_schema.touch_status() RETURNS trigger LANGUAGE plpgsql AS $fn$
BEGIN
  RETURN NEW;
END;
$fn$;

CREATE PROCEDURE db_pull_schema.log_noop() LANGUAGE plpgsql AS $$ BEGIN NULL; END $$;

-- tables
CREATE TABLE db_pull_schema.customers (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  full_name text,
  norm text DEFAULT db_pull_schema.norm_email('X@Y'),
  norm_gen text GENERATED ALWAYS AS (db_pull_schema.norm_email(email)) STORED,
  code text COLLATE "C",
  status db_pull_schema.order_status NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT customers_email_key UNIQUE (email),
  CONSTRAINT customers_email_check CHECK (position('@' in email) > 1),
  CONSTRAINT customers_dollar_check CHECK (email <> 'a$$b'),
  CONSTRAINT customers_tag_check CHECK (email <> 'x$supalite$y')
);
ALTER TABLE db_pull_schema.customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY customers_self ON db_pull_schema.customers USING (true);
CREATE INDEX customers_email_norm_idx ON db_pull_schema.customers ((db_pull_schema.norm_email(email)));
CREATE UNIQUE INDEX customers_full_name_uidx ON db_pull_schema.customers (full_name);

CREATE TABLE db_pull_schema.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 500 INCREMENT BY 2 MAXVALUE 900000) PRIMARY KEY,
  legacy_id integer NOT NULL DEFAULT nextval('db_pull_schema.legacy_id_seq'),
  qty db_pull_schema.positive_int,
  customer_id bigint NOT NULL,
  ext_id bigint,
  total numeric(12,2) NOT NULL DEFAULT 0,
  total_with_tax numeric(12,2) GENERATED ALWAYS AS (total * 1.1) STORED,
  status db_pull_schema.order_status NOT NULL DEFAULT 'pending',
  CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES db_pull_schema.customers(id),
  CONSTRAINT orders_ext_id_fkey FOREIGN KEY (ext_id) REFERENCES db_pull_ext.ext_ref(id),
  CONSTRAINT orders_total_check CHECK (total >= 0),
  CONSTRAINT orders_norm_check CHECK (db_pull_schema.norm_email(status::text) IS NOT NULL),
  CONSTRAINT orders_legacy_id_excl EXCLUDE (legacy_id WITH =)
);
ALTER SEQUENCE db_pull_schema.legacy_id_seq OWNED BY db_pull_schema.orders.legacy_id;
CREATE INDEX orders_status_idx ON db_pull_schema.orders (status);

CREATE TRIGGER orders_touch_status BEFORE UPDATE ON db_pull_schema.orders
FOR EACH ROW EXECUTE FUNCTION db_pull_schema.touch_status();

CREATE CONSTRAINT TRIGGER orders_ct AFTER INSERT ON db_pull_schema.orders
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION db_pull_schema.touch_status();

CREATE TABLE db_pull_schema.snapshots (
  snap db_pull_schema.customers,
  taken_at timestamptz DEFAULT now()
);

CREATE TABLE db_pull_schema."CamelTable" (
  "order" text,
  "weird""col" text,
  CONSTRAINT "Check Me" CHECK ("order" IS NULL OR length("order") > 0)
);

CREATE UNLOGGED TABLE db_pull_schema.session_cache (
  key text PRIMARY KEY,
  value text
);

-- table-stage functions
CREATE FUNCTION db_pull_schema.order_count(p_customer_id bigint) RETURNS bigint
LANGUAGE sql STABLE AS $$ SELECT count(*) FROM db_pull_schema.orders WHERE customer_id = p_customer_id $$;

CREATE FUNCTION db_pull_schema.user_rows() RETURNS SETOF db_pull_schema.customers
LANGUAGE sql STABLE AS $$ SELECT * FROM db_pull_schema.customers $$;

-- views
CREATE VIEW db_pull_schema.paid_orders AS
  SELECT o.id, o.customer_id, o.total FROM db_pull_schema.orders o WHERE o.status = 'paid';
CREATE VIEW db_pull_schema.paid_order_totals AS
  SELECT customer_id, sum(total) AS total FROM db_pull_schema.paid_orders GROUP BY customer_id;
CREATE VIEW db_pull_schema.safe_orders WITH (security_barrier) AS
  SELECT id, customer_id FROM db_pull_schema.orders;

-- view-stage functions
CREATE FUNCTION db_pull_schema.paid_orders_all() RETURNS SETOF db_pull_schema.paid_orders
LANGUAGE sql STABLE AS $$ SELECT * FROM db_pull_schema.paid_orders $$;

CREATE FUNCTION db_pull_schema.get_paid(OUT o db_pull_schema.paid_orders)
LANGUAGE plpgsql AS $$ BEGIN SELECT p INTO o FROM db_pull_schema.paid_orders p LIMIT 1; END $$;

-- materialized views
CREATE MATERIALIZED VIEW db_pull_schema.order_totals_mv AS
  SELECT customer_id, sum(total) AS total FROM db_pull_schema.orders GROUP BY customer_id;
CREATE UNIQUE INDEX order_totals_mv_uidx ON db_pull_schema.order_totals_mv (customer_id);
CREATE MATERIALIZED VIEW db_pull_schema.empty_mv AS
  SELECT id FROM db_pull_schema.orders WITH NO DATA;

-- footer exercisers: partition hierarchy, FK to partitioned parent, aggregate + dependent view
CREATE TABLE db_pull_schema.events_partitioned (
  id bigint NOT NULL,
  created_at timestamptz NOT NULL,
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);
CREATE TABLE db_pull_schema.events_p1 PARTITION OF db_pull_schema.events_partitioned
  FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE db_pull_schema.events_ref (
  id bigint PRIMARY KEY,
  event_id bigint,
  event_created timestamptz,
  CONSTRAINT events_ref_event_fkey FOREIGN KEY (event_id, event_created)
    REFERENCES db_pull_schema.events_partitioned (id, created_at)
);
CREATE VIEW db_pull_schema.events_view AS SELECT * FROM db_pull_schema.events_partitioned;
CREATE FUNCTION db_pull_schema.evt_rows() RETURNS SETOF db_pull_schema.events_partitioned
LANGUAGE sql STABLE AS $$ SELECT * FROM db_pull_schema.events_partitioned $$;
CREATE DOMAIN db_pull_schema.cust_dom AS db_pull_schema.customers;
CREATE DOMAIN db_pull_schema.cust_dom2 AS db_pull_schema.cust_dom;
CREATE TABLE db_pull_schema.evt_holder (evt db_pull_schema.events_partitioned);

CREATE AGGREGATE db_pull_schema.agg_sum(bigint) (SFUNC = int8pl, STYPE = bigint);
CREATE VIEW db_pull_schema.agg_totals AS
  SELECT db_pull_schema.agg_sum(o.id) AS s FROM db_pull_schema.orders o;
